### ISSUE TITLE
Create Videos page

### ISSUE THREAD

**Issue by thaingu** [codersforcauses/foodbank#29]
Requirements:

- Video page will embed some videos from the Superhero Foods YouTube channel: https://www.youtube.com/user/FoodbankWA/videos
- Styling should be similar to the rest of the web app.
- A way to navigate for different videos.

**Comment by Drewbi** [comment]
@AaronTYT For this task we can either display videos in a grid and then expand when clicked into a popup or a separate page, or have a carousel view with the videos or some other arrangement. The approach is really whatever you think would be best. Keep in mind these videos are primarily for children so the ui should be easy to use and fairly information free.

**Comment by AaronTYT** [comment]
@Drewbi what kind of topics or components should I include for the videos page?

**Comment by Drewbi** [comment]
I wouldn't worry about the sub-tasks for this one, I've removed the `epic` label because i think only one person needs to work on this. 

Basically it will either be a single page with many video players on it, or a list of videos in a list where clicking on one will take you to a new page. The choice is yours :)

**Comment by CodeWithTheDoctor** [comment]
No longer in scope of the project.
